# Generated by Django 3.1.7 on 2021-09-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('cod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=10)),
                ('clave', models.CharField(max_length=10)),
                ('nombre_completo', models.CharField(max_length=200)),
            ],
        ),
    ]
