# Generated by Django 3.2.6 on 2022-02-04 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('ruc_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=30)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('genero_cliente', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('codigo_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('razon_social_proveedor', models.CharField(max_length=50)),
                ('ruc_proveedor', models.CharField(max_length=50)),
                ('telefono_proveedor', models.CharField(max_length=30)),
                ('direccion_proveedor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Gabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=10, unique=True)),
                ('password_usuario', models.CharField(max_length=10)),
                ('nombre_completo_usuario', models.CharField(max_length=200)),
                ('tipo_usuario', models.IntegerField(null=True)),
                ('ci_usuario', models.CharField(max_length=20)),
                ('telefono_usuario', models.CharField(max_length=30)),
                ('direccion_usuario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('id_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('cod_repuesto', models.IntegerField(null=True)),
                ('tipo_repuesto', models.IntegerField(null=True)),
                ('marca_repuesto', models.CharField(max_length=30)),
                ('descripcion_repuesto', models.CharField(max_length=200)),
                ('precio_compra_repuesto', models.IntegerField()),
                ('precio_venta_repuesto', models.IntegerField()),
                ('stock_repuesto', models.IntegerField(default=0)),
                ('imagen_repuesto', models.ImageField(null=True, upload_to='repuestos')),
                ('nombre_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('codigo_rep', models.AutoField(primary_key=True, serialize=False)),
                ('equipo_rep', models.IntegerField(null=True)),
                ('desc_equipo_rep', models.CharField(max_length=200)),
                ('horas_rep', models.IntegerField(null=True)),
                ('actividades_rep', models.CharField(max_length=200)),
                ('inicio_rep', models.DateField()),
                ('fin_rep', models.DateField()),
                ('estado_rep', models.IntegerField(default=1, null=True)),
                ('nombre_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.cliente')),
                ('nombre_completo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id_periferico', models.AutoField(primary_key=True, serialize=False)),
                ('cod_periferico', models.IntegerField(null=True)),
                ('tipo_periferico', models.IntegerField(null=True)),
                ('marca_periferico', models.CharField(max_length=30)),
                ('descripcion_periferico', models.CharField(max_length=200)),
                ('precio_compra_periferico', models.IntegerField()),
                ('precio_venta_periferico', models.IntegerField()),
                ('stock_periferico', models.IntegerField(default=0)),
                ('imagen_periferico', models.ImageField(null=True, upload_to='perifericos')),
                ('nombre_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('codigo_mant', models.AutoField(primary_key=True, serialize=False)),
                ('equipo_mant', models.IntegerField(null=True)),
                ('desc_equipo_mant', models.CharField(max_length=200)),
                ('horas_mant', models.IntegerField(null=True)),
                ('actividades_mant', models.CharField(max_length=200)),
                ('inicio_mant', models.DateField()),
                ('fin_mant', models.DateField()),
                ('estado_mant', models.IntegerField(default=1, null=True)),
                ('nombre_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.cliente')),
                ('nombre_completo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='descripcion_nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.nacionalidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.departamento'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nombre_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.departamento'),
        ),
    ]
