# Generated by Django 3.2.6 on 2022-02-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perifericos',
            old_name='codigo_periferico',
            new_name='cod_periferico',
        ),
    ]
