# Generated by Django 3.2.8 on 2022-02-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='talonario_ventas',
        ),
    ]
