# Generated by Django 3.2.7 on 2021-11-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
