# Generated by Django 3.2.8 on 2022-02-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0002_delete_talonario_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='talonario_ventas',
            fields=[
                ('id_talonario_venta', models.AutoField(primary_key=True, serialize=False)),
                ('nro_inicio_factura_venta', models.IntegerField()),
                ('nro_actual_factura_venta', models.IntegerField()),
                ('nro_fin_factura_venta', models.IntegerField()),
                ('nro_timbrado_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.timbrado_venta')),
            ],
        ),
    ]
