# Generated by Django 3.2.7 on 2021-11-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0002_delete_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
