# Generated by Django 3.2.8 on 2022-02-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0002_rename_nombre_cliente_mantenimiento_ruc_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='ruc_cliente',
            new_name='nombre_cliente',
        ),
    ]
