# Generated by Django 3.2.6 on 2022-02-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0002_factura_venta_factura_venta_detalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='talonario_venta',
            new_name='talonario_ventas',
        ),
    ]
