# Generated by Django 3.2.6 on 2022-02-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0002_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='nombre_proveedor',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='tipo_ram',
        ),
        migrations.DeleteModel(
            name='Tipo_Cpu',
        ),
        migrations.DeleteModel(
            name='Tipo_Gabinete',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='Tipo_Ram',
        ),
    ]
