# Generated by Django 3.2.6 on 2022-02-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0002_rename_codigo_periferico_perifericos_cod_periferico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perifericos',
            name='tipo_periferico',
            field=models.IntegerField(null=True),
        ),
    ]
