# Generated by Django 3.2.6 on 2022-02-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0002_rename_nombre_cliente_mantenimiento_ruc_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
    ]
