# Generated by Django 3.2.8 on 2022-02-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0003_talonario_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura_venta_detalle',
            name='id_factura_venta',
        ),
        migrations.RemoveField(
            model_name='factura_venta_detalle',
            name='id_periferico',
        ),
        migrations.RemoveField(
            model_name='talonario_ventas',
            name='nro_timbrado_venta',
        ),
        migrations.DeleteModel(
            name='factura_venta',
        ),
        migrations.DeleteModel(
            name='factura_venta_detalle',
        ),
        migrations.DeleteModel(
            name='talonario_ventas',
        ),
        migrations.DeleteModel(
            name='timbrado_venta',
        ),
    ]
