# Generated by Django 3.2.6 on 2022-02-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0003_delete_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('codigo_mant', models.AutoField(primary_key=True, serialize=False)),
                ('equipo_mant', models.IntegerField(null=True)),
                ('desc_equipo_mant', models.CharField(max_length=200)),
                ('horas_mant', models.IntegerField(null=True)),
                ('actividades_mant', models.CharField(max_length=200)),
                ('inicio_mant', models.DateField()),
                ('fin_mant', models.DateField()),
                ('estado_mant', models.IntegerField(default=1, null=True)),
                ('nombre_completo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.usuario')),
                ('ruc_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.cliente')),
            ],
        ),
    ]
