# Generated by Django 3.2.6 on 2022-01-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0004_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('codigo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('ruc_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.IntegerField()),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('genero_cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
