# Generated by Django 3.2.6 on 2022-02-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0004_tipo_cpu_tipo_gabinete_tipo_ram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_cpu',
            old_name='tipo_cpu',
            new_name='desc_tipo_cpu',
        ),
        migrations.RenameField(
            model_name='tipo_ram',
            old_name='tipo_ram',
            new_name='desc_tipo_ram',
        ),
        migrations.RemoveField(
            model_name='tipo_gabinete',
            name='tipo_gabinete',
        ),
        migrations.AddField(
            model_name='tipo_gabinete',
            name='desc_tipo_gabinete',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id_ram', models.AutoField(primary_key=True, serialize=False)),
                ('cod_ram', models.IntegerField(null=True)),
                ('marca_ram', models.CharField(max_length=30)),
                ('descripcion_ram', models.CharField(max_length=200)),
                ('precio_compra_ram', models.IntegerField()),
                ('precio_venta_ram', models.IntegerField()),
                ('stock_ram', models.IntegerField(default=0)),
                ('imagen_ram', models.ImageField(null=True, upload_to='ram')),
                ('nombre_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.proveedor')),
                ('tipo_ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.tipo_ram')),
            ],
        ),
    ]
