# Generated by Django 3.2.6 on 2022-02-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0005_rename_ruc_cliente_mantenimiento_nombre_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('codigo_rep', models.AutoField(primary_key=True, serialize=False)),
                ('equipo_rep', models.IntegerField(null=True)),
                ('desc_equipo_rep', models.CharField(max_length=200)),
                ('horas_rep', models.IntegerField(null=True)),
                ('actividades_rep', models.CharField(max_length=200)),
                ('inicio_rep', models.DateField()),
                ('fin_rep', models.DateField()),
                ('estado_rep', models.IntegerField(default=1, null=True)),
                ('nombre_completo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.usuario')),
            ],
        ),
    ]
