# Generated by Django 3.2.6 on 2022-01-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0005_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero_cliente',
            field=models.IntegerField(null=True),
        ),
    ]
