# Generated by Django 3.2.6 on 2022-02-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0005_auto_20220221_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='stock_min_cpu',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='stock_min_gab',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='perifericos',
            name='stock_min_periferico',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='placa_base',
            name='stock_min_placa_base',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ram',
            name='stock_min_ram',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='repuestos',
            name='stock_min_repuesto',
            field=models.IntegerField(default=5),
        ),
    ]
