# Generated by Django 3.2.6 on 2022-02-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0005_auto_20220204_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placa_base',
            fields=[
                ('id_placa_base', models.AutoField(primary_key=True, serialize=False)),
                ('cod_placa_base', models.IntegerField(null=True)),
                ('marca_placa_base', models.CharField(max_length=30)),
                ('descripcion_placa_base', models.CharField(max_length=200)),
                ('precio_compra_placa_base', models.IntegerField()),
                ('precio_venta_placa_base', models.IntegerField()),
                ('stock_placa_base', models.IntegerField(default=0)),
                ('imagen_placa_base', models.ImageField(null=True, upload_to='placa_base')),
                ('nombre_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.proveedor')),
                ('tipo_cpu_placa_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.tipo_cpu')),
                ('tipo_gabinete_placa_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.tipo_gabinete')),
                ('tipo_ram_placa_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.tipo_ram')),
            ],
        ),
    ]
