# Generated by Django 3.2.6 on 2022-01-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0006_alter_cliente_genero_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('codigo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('razon_social_proveedor', models.CharField(max_length=50)),
                ('ruc_proveedor', models.CharField(max_length=50)),
                ('telefono_proveedor', models.IntegerField()),
                ('direccion_proveedor', models.CharField(max_length=50)),
            ],
        ),
    ]
