# Generated by Django 3.2.6 on 2022-02-02 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0006_reparacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id_periferico', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_periferico', models.IntegerField(null=True)),
                ('tipo_periferico', models.CharField(max_length=50)),
                ('marca_periferico', models.CharField(max_length=30)),
                ('descripcion_periferico', models.CharField(max_length=200)),
                ('precio_compra_periferico', models.CharField(max_length=50)),
                ('precio_venta_periferico', models.CharField(max_length=50)),
                ('stock_periferico', models.SmallIntegerField(default=0)),
                ('nombre_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.proveedor')),
            ],
        ),
    ]
