# Generated by Django 3.2.6 on 2022-02-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0006_auto_20220221_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria_Modificar',
            fields=[
                ('id_auditoria_modificar', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_modificada', models.CharField(max_length=80, null=True)),
                ('id_modificado', models.IntegerField(null=True)),
                ('usuario_modificador', models.CharField(max_length=50, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
