# Generated by Django 3.2.6 on 2022-02-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0008_montaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montaje',
            old_name='tipo_periferico',
            new_name='id_periferico',
        ),
    ]
