# Generated by Django 3.2.8 on 2022-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0008_alter_auditoria_modificar_usuario_modificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria_modificar',
            name='usuario_modificador',
            field=models.IntegerField(null=True),
        ),
    ]
