# Generated by Django 3.2.6 on 2022-01-26 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0008_auto_20220120_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('codigo_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('nombre_departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.departamento')),
            ],
        ),
    ]
