# Generated by Django 3.2.6 on 2022-01-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0009_ciudad_departamento_nacionalidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='nombre_departamento',
            new_name='nombre_departamento_id',
        ),
    ]
