# Generated by Django 3.2.6 on 2022-01-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0010_rename_nombre_departamento_ciudad_nombre_departamento_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='nombre_departamento_id',
            new_name='nombre_departamento',
        ),
    ]
