# Generated by Django 3.2.6 on 2022-02-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0011_rename_id_placa_base_montaje_placa_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montaje',
            old_name='placa_base',
            new_name='id_placa_base',
        ),
    ]
