# Generated by Django 3.2.8 on 2022-01-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0011_rename_nombre_departamento_id_ciudad_nombre_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descripcion_nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.nacionalidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.departamento'),
        ),
    ]
