# Generated by Django 3.2.6 on 2022-01-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0012_auto_20220127_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(max_length=30),
        ),
    ]
