# Generated by Django 3.2.8 on 2022-01-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0013_alter_cliente_telefono_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ci_usuario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_usuario',
            field=models.CharField(max_length=30),
        ),
    ]
