# Generated by Django 3.2.6 on 2022-01-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0014_auto_20220128_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.CharField(max_length=30),
        ),
    ]
