# Generated by Django 3.2.6 on 2022-02-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0014_rename_placa_base_montaje_placa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montaje',
            old_name='placa',
            new_name='placa_base',
        ),
    ]
