# Generated by Django 3.2.6 on 2022-01-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0015_alter_proveedor_telefono_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('codigo_mant', models.AutoField(primary_key=True, serialize=False)),
                ('equipo_mant', models.IntegerField(null=True)),
                ('desc_equipo_mant', models.CharField(max_length=200)),
                ('horas_mant', models.IntegerField(null=True)),
                ('actividades_mant', models.CharField(max_length=200)),
                ('inicio_mant', models.DateField()),
                ('fin_mant', models.DateField()),
                ('nombre_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.cliente')),
                ('nombre_completo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.usuario')),
            ],
        ),
    ]
