# Generated by Django 3.2.6 on 2022-01-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0016_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_mant',
            field=models.IntegerField(null=True),
        ),
    ]
