# Generated by Django 3.2.6 on 2022-01-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0017_mantenimiento_estado_mant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado_mant',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
