# Generated by Django 3.2.6 on 2022-01-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0018_alter_mantenimiento_estado_mant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fin_mant',
            field=models.DateField(null=True),
        ),
    ]
