# Generated by Django 3.2.6 on 2022-02-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0018_auto_20220215_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura_compra',
            old_name='id_proveedor',
            new_name='codigo_proveedor',
        ),
    ]
