# Generated by Django 3.2.8 on 2022-02-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0019_rename_id_proveedor_factura_compra_codigo_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timbrado',
            old_name='id_proveedor',
            new_name='codigo_proveedor',
        ),
    ]
