# Generated by Django 3.2.6 on 2022-02-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0020_rename_id_proveedor_timbrado_codigo_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='timbrado_venta',
            fields=[
                ('nro_timbrado_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fch_vencimiento_timbrado_venta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='factura_venta',
            fields=[
                ('id_factura_venta', models.AutoField(primary_key=True, serialize=False)),
                ('nro_inicio_factura_venta', models.IntegerField()),
                ('nro_actual_factura_venta', models.IntegerField()),
                ('nro_fin_factura_venta', models.IntegerField()),
                ('nro_timbrado_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pagina.timbrado_venta')),
            ],
        ),
    ]
